### PR TITLE
Color picker ui updates and added a title text label

### PR DESCRIPTION
**Pull request by zhaoli1211**
made save and cancel button public in order to change their appearance outside the library
add a public  text label where we can set the title for the color picker view
change color circle UI
change color circle size
change color circle line spacing

design link: [zpl.io/V0JzvRE](url)

screen shot 2018-11-27 at 1 52 02 pm

Before:

screen shot 2018-11-27 at 1 57 50 pm

After:
screen shot 2018-11-27 at 3 21 38 pm

### CODE REVIEW

**Comment by plflanagan** [comment]
Thanks for adding the design link. Could you provide some screenshots. Ideal would be before and after (labeled as such). If that's too tedious at this point, then the update would be enough

**Comment by plflanagan** [comment]
Thanks for the photos. Do you know why the label is overlapping with the cancel button?

**Comment by plflanagan** [comment]
Oh, and will the label say "Change Background Color" like in the design? If so, could you do that in this PR. If not...then...what's the label for? :)

**Comment by zhaoli1211** [comment]
because we won't need the cancel button base on the new design, but we might need it in the future. so I made them public, we can hide one of them as needed

**Comment by plflanagan** [comment]
Conversation on Slack starting at https://teamunum.slack.com/archives/CE8RVJ54Z/p1543358970002000 makes it sound like we will keep the cancel button FYI.

**Review by plflanagan — APPROVED** [review]

**Pull request merged**
